name: Integration Test odfe-cli
on:
  push:
    branches:
      - main
      - opendistro-*
  pull_request:
    branches:
      - main
      - opendistro-*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        odfe-version: [ 1.12.0 ]
    steps:
      - name: Set up Go ubuntu-latest
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run Docker Image
        env:
          ODFE_VERSION: ${{ matrix.odfe-version }}
        run: |
          make docker.start.components
          sleep 60

      - name: Run Integration Tests
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test.integration